default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary: &primary_development
    <<: *default
    <% if ENV['USE_RENDER_DB'] == 'true' %>
    host: <%= ENV['DB_HOST'] || 'dpg-d7f0kknaqgkc739uphc0-a' %>
    database: <%= ENV['DB_NAME'] || 'marlai_santhe_002' %>
    username: <%= ENV['DB_USERNAME'] || 'marlai_santhe_002_user' %>
    password: <%= ENV['DB_PASSWORD'] || 'P4SP9kfmdhOiqCjT5z8FGHTYmDkODaHm' %>
    <% else %>
    database: <%= ENV['DB_NAME'] || 'ecommerce_store_development' %>
    username: <%= ENV['DB_USERNAME'] || 'mahadev-bhat' %>
    <% end %>
    port: <%= ENV['DB_PORT'] || 5432 %>
  cable:
    <<: *primary_development
  queue:
    <<: *primary_development
  cache:
    <<: *primary_development

test:
  primary: &primary_test
    <<: *default
    database: marali_sante_test
  cable:
    <<: *primary_test
  queue:
    <<: *primary_test
  cache:
    <<: *primary_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://marlai_santhe_002_user:P4SP9kfmdhOiqCjT5z8FGHTYmDkODaHm@dpg-d7f0kknaqgkc739uphc0-a/marlai_santhe_002' %>
    host: <%= ENV['DB_HOST'] || 'dpg-d7f0kknaqgkc739uphc0-a' %>
    database: <%= ENV['DB_NAME'] || 'marlai_santhe_002' %>
    username: <%= ENV['DB_USERNAME'] || 'marlai_santhe_002_user' %>
    password: <%= ENV['DB_PASSWORD'] || 'P4SP9kfmdhOiqCjT5z8FGHTYmDkODaHm' %>
    port: <%= ENV['DB_PORT'] || 5432 %>
  cable:
    <<: *primary_production
  queue:
    <<: *primary_production
  cache:
    <<: *primary_production